### ISSUE TITLE
Having trouble getting it working

### ISSUE THREAD

**Issue by abienz** [AlimovSV/svg-sprite-brunch#1]
Hi, I'm not sure I understand how to get this plugin working...

The steps I'm following:

1. install via npm
2. add sprites to app/assets/svg/
3. run brunch watch
4. No svg sprite is created.
5. add svgsprite: {mode: {symbol: {dest: 'public/svg', sprite: 'sprite.svg'}}} to brunch.config
6. Restart brunch watch
7. No svg sprite is created.

I do still get my svg files moved to an svg folder inside public, so the files are not ignored.

Do I need to create another config for svg-sprite directly?

Any help would be really appreciated.

**Comment by AlimovSV** [comment]
Please check the [example](https://github.com/AlimovSV/svg-sprite-brunch-example).

**Comment by mradke** [comment]
@abienz I also tripped over this. It is imperative that you define the regex for `conventions.assets` correctly:

```
conventions: {
    // This option sets where we should place non-css and non-js assets in.
    // By default, we set this to "/src/assets". Files in this directory
    // will be copied to `paths.public`, which is "public" by default.
    assets: /^(src\/assets\/(?!svg))/
}
```

Now I was under the impression that this regex looks for the svg **file extension**. This assumption proved to be wrong. The last part is a negative lookahead which excludes this specified directory from beeing copied.

In my case for example, I placed the source files under `app/assets/icons/`, hence the following definition is necessary:

```
conventions: {
  assets: /^(app\/assets\/(?!icons))/
}
```

**Comment by abienz** [comment]
That was the problem, I didn't have a convention set in my brunch-config.js.

Most other plugins I've used have been zero configuration so I didn't respect the instructions on the github page. It might be nice to state that the convention configuration is required.

Thanks for the help @mradke and @AlimovSV
